export default [
  "Pentzia incana",
  "Alnus",
  "Alnus glutinosa",
  "Ilex verticillata",
  "Alnus glutinosa",
  "Ilex verticillata",
  "Alnus incana",
  "Alnus incana",
  "Ilex verticillata",
  "Alnus incana",
  "Alnus rhombifolia",
  "Ilex verticillata",
  "Prunus dulcis",
  "Ambrosia trifida",
  "Apocynum cannabinum",
  "Brugmansia suaveolens",
  "Malus domestica",
  "Rhanterium epapposum",
  "Cornus florida",
  "Cornus florida",
  "Fraxinus",
  "Acer negundo",
  "Fraxinus nigra",
  "Fraxinus quadrangulata",
  "Fraxinus americana",
  "Fraxinus excelsior",
  "Fraxinus pennsylvanica",
  "Acer negundo",
  "Fraxinus pennsylvanica",
  "Fraxinus pennsylvanica",
  "Fraxinus pennsylvanica",
  "Fraxinus americana",
  "Acer negundo",
  "Fraxinus pennsylvanica",
  "Azolla",
  "Azolla caroliniana",
  "Adansonia",
  "Fabaceae",
  "Phaseolus",
  "Ilex decidua",
  "Veratrum viride",
  "Solanum dulcamara",
  "Daucus carota",
  "Daucus carota",
  "Strelitzia reginae",
  "Betula",
  "Betula lenta",
  "Betula nigra",
  "Betula papyrifera",
  "Betula papyrifera",
  "Betula lenta",
  "Betula pendula",
  "Betula pendula",
  "Betula alleghaniensis",
  "Betula lenta",
  "Betula papyrifera",
  "Betula nigra",
  "Betula nigra",
  "Betula lenta",
  "Betula papyrifera",
  "Betula lenta",
  "Betula lenta",
  "Betula nigra",
  "Betula pendula",
  "Betula papyrifera",
  "Betula pendula",
  "Betula alleghaniensis",
  "Barbarea vulgaris",
  "Cardamine bulbosa",
  "Cardamine hirsuta",
  "Cardamine hirsuta",
  "Solanum dulcamara",
  "Solanum dulcamara",
  "Ambrosia",
  "Ambrosia artemisiifolia",
  "Artemisia trifida",
  "Helenium amarum",
  "Rubus",
  "Rubus pensilvanicus",
  "Rubus occidentalis",
  "Rubus hispidus",
  "Rubus pensilvanicus",
  "Rubus hispidus",
  "Rubus occidentalis",
  "Rudbeckia hirta",
  "Rudbeckia fulgida",
  "Viburnum prunifolium",
  "Rudbeckia hirta",
  "Ambrosia artemisiifolia",
  "Hyacinthoides non-scripta",
  "Allium caeruleum",
  "Maclura pomifera",
  "Buxus",
  "Cornus florida",
  "Acer negundo",
  "Buxus",
  "Cornus florida",
  "Cornus florida",
  "Solanum carolinense",
  "Encelia farinosa",
  "Plantago major",
  "Rudbeckia hirta",
  "Rudbeckia hirta",
  "Rudbeckia triloba",
  "Ambrosia trifida",
  "Ajuga reptans",
  "Asclepias syriaca",
  "Asclepias tuberosa",
  "Brassica oleracea",
  "Symplocarpus foetidus",
  "Symplocarpus foetidus",
  "Symplocarpus foetidus",
  "Lysichiton",
  "Symplocarpus foetidus",
  "Platanus racemosa",
  "Asclepias tuberosa",
  "Phytolacca americana",
  "Daucus carota",
  "Daucus carota",
  "Ambrosia artemisiifolia",
  "Plantago major",
  "Lyonothamnus floribundus",
  "Polygala calcarea",
  "Sinapis arvensis",
  "Prunus",
  "Prunus serotina",
  "Prunus serotina",
  "Prunus serotina",
  "Prunus serotina",
  "Prunus avium",
  "Prunus serotina",
  "Prunus serotina",
  "Asclepias tuberosa",
  "Dendranthema grandiflora",
  "vi",
  "Chrysanthemum morifolium",
  "Cinnamomum verum",
  "Phytolacca americana",
  "Coffea",
  "Corydalis flavula",
  "Symplocarpus foetidus",
  "Aquilegia vulgaris",
  "Sonchus oleraceus",
  "Rudbeckia fulgida",
  "Rudbeckia laciniata",
  "Rudbeckia fulgida",
  "Rudbeckia laciniata",
  "Rudbeckia fulgida",
  "Rudbeckia laciniata",
  "Rudbeckia triloba",
  "Rudbeckia triloba",
  "Cornus amomum",
  "Cornus amomum",
  "Cornus florida",
  "Cornus florida",
  "Corydalis",
  "Corydalis chelidoniifolia",
  "Corydalis aurea",
  "Corydalis flavula",
  "Corydalis sempervirens",
  "Corydalis sempervirens",
  "Corydalis lutea",
  "Corydalis flavula",
  "Gossypium",
  "Rorippa sylvestris",
  "Barbarea verna",
  "Barbarea verna",
  "Barbarea verna",
  "Barbarea verna",
  "Cardamine bulbosa",
  "Cardamine hirsuta",
  "Barbarea verna",
  "Cardamine hirsuta",
  "Barbarea verna",
  "Cardamine bulbosa",
  "Barbarea verna",
  "Cardamine concatenata",
  "Daucus carota",
  "Cardamine concatenata",
  "Rudbeckia hirta",
  "Bellis perennis",
  "Lamium",
  "Lamium amplexicaule",
  "Lamium purpureum",
  "Lamium maculatum",
  "Veratrum viride",
  "Clematis virginiana",
  "Clematis virginiana",
  "Daucus carota",
  "Rubus hispidus",
  "Rubus hispidus",
  "Sonchus arvensis",
  "Cornus",
  "Cornus florida",
  "Cornus florida",
  "Cornus florida",
  "Cornus kousa",
  "Cornus kousa",
  "Moringa oleifera",
  "Cornus nuttallii",
  "Cornus amomum",
  "Cornus amomum",
  "Veratrum viride",
  "Solanum nigrum",
  "Durio zibethinus",
  "Durio testudinarius",
  "Durio grandiflorus",
  "Durio kutejensis",
  "Durio dulcis",
  "Ilex glabra",
  "Cattleya schroederae",
  "Veratrum viride",
  "Sambucus",
  "Lupinus elegans",
  "Dillenia indica",
  "Rudbeckia hirta",
  "Eucalyptus",
  "Vaccinium ovatum",
  "Encalypta",
  "Amphipappus",
  "Achillea ptarmica",
  "Azolla caroliniana",
  "Solanum dulcamara",
  "Solanum dulcamara",
  "Solanum dulcamara",
  "Foeniculum vulgare",
  "Nephrolepis exaltata",
  "Polystichum acrostichoides",
  "Polypodium scouleri",
  "Nephrolepis obliterata",
  "Azolla caroliniana",
  "Polystichum",
  "Azolla caroliniana",
  "Polystichum munitum",
  "Ilex verticillata",
  "Tanacetum parthenium",
  "Myosotis arvensis",
  "Ficus",
  "Ficus carica",
  "Linum usitatissimum",
  "Phormium tenax",
  "Phormium colensoi",
  "Asclepias tuberosa",
  "Digitalis purpurea",
  "Corydalis flavula",
  "Ilex glabra",
  "Phytolacca americana",
  "Allium moly",
  "Allium canadense",
  "Alliaria petiolata",
  "Alliaria petiolata",
  "Veronica chamaedrys",
  "Hesperis matronalis",
  "Hesperis matronalis",
  "Hesperis matronalis",
  "Hesperis matronalis",
  "Hesperis matronalis",
  "Tanacetum vulgare",
  "Laburnum",
  "Rudbeckia laciniata",
  "Rudbeckia hirta",
  "Achillea millefolium",
  "Achillea ptarmica",
  "Vitis",
  "Solanum opacum",
  "Rubus hispidus",
  "Rubus hispidus",
  "Sonchus arvensis",
  "Curcuma domestica",
  "Corydalis sempervirens",
  "Corydalis flavula",
  "Ambrosia artemisiifolia",
  "Artemisia trifida",
  "Plantago major",
  "Maclura pomifera",
  "Helleborus",
  "Veratrum viride",
  "Veratrum viride",
  "Veratrum nigrum",
  "Veratrum album",
  "Veratrum album",
  "Veratrum viride",
  "Veratrum viride",
  "Veratrum album",
  "Veratrum viride",
  "Cannabis",
  "Cannabis sativa",
  "Apocynum cannabinum",
  "Plantago major",
  "Barbarea vulgaris",
  "Ambrosia artemisiifolia",
  "Ilex",
  "Ilex decidua",
  "Ilex verticillata",
  "Ilex aquifolium",
  "Ilex glabra",
  "Ilex decidua",
  "Ilex decidua",
  "Ilex verticillata",
  "Lunaria annua",
  "Ambrosia trifida",
  "Solanum nigrum",
  "Vaccinium",
  "Vaccinium ovatum",
  "Vaccinium parvifolium",
  "Sempervivum tectorum",
  "Apocynum cannabinum",
  "Cannabis indica",
  "Asclepias incarnata",
  "Castilleja",
  "Castilleja mutis",
  "Asclepias tuberosa",
  "Asclepias tuberosa",
  "Ilex glabra",
  "Phytolacca americana",
  "Acacia estrophiolata",
  "Coincya monensis",
  "Veratrum viride",
  "Hedera",
  "Alliaria petiolata",
  "Alliaria petiolata",
  "Jasminum officinale",
  "Ludisia discolor",
  "Juncus kraussii",
  "Adenanthos obovatus",
  "Amelanchier canadensis",
  "Rorippa sylvestris",
  "Ptisana salicina",
  "Cornus amomum",
  "Veronica bullii",
  "Reynoutria japonica",
  "Cornus kousa",
  "Pueraria montana",
  "Pomaderris kumeraho",
  "Daucus carota",
  "Asparagus setaceus",
  "Alchemilla mollis",
  "Cardamine pratensis",
  "Plantago major",
  "Phoenicophorium",
  "Magnolia splendens",
  "Lavandula",
  "Allium",
  "Lilium catesbaei",
  "Agapanthus praecox",
  "Allium moly",
  "Hesperis matronalis",
  "Helianthella",
  "Erigeron cavernensis",
  "Clematis virginiana",
  "Acer",
  "Acer negundo",
  "Acer nigrum",
  "Acer saccharinum",
  "Acer negundo",
  "Acer negundo",
  "Acer pensylvanicum",
  "Acer negundo",
  "Acer saccharinum",
  "Acer saccharinum",
  "Acer saccharinum",
  "Acer saccharinum",
  "Acer pensylvanicum",
  "Acer saccharum",
  "Acer barbatum",
  "Acer leucoderme",
  "Acer saccharinum",
  "Acer saccharinum",
  "Acer saccharinum",
  "Prosopis",
  "Prosopis glandulosa",
  "Prosopis pubescens",
  "Achillea millefolium",
  "Asclepias",
  "Sonchus oleraceus",
  "Asclepias amplexicaulis",
  "Asclepias syriaca",
  "Asclepias verticillata",
  "Asclepias tuberosa",
  "Asclepias incarnata",
  "Asclepias incarnata",
  "Asclepias verticillata",
  "Asclepias tuberosa",
  "Sonchus oleraceus",
  "Acer pensylvanicum",
  "Solanum nigrum",
  "Solanum opacum",
  "Azolla caroliniana",
  "Hesperis matronalis",
  "Betula lenta",
  "Morus",
  "Morus rubra",
  "Morus alba",
  "Epacris longiflora",
  "Asplenium flabellifolium",
  "Urtica dioica",
  "Solanum carolinense",
  "Solanum carolinense",
  "Solanum carolinense",
  "Hylocereus",
  "Phytolacca americana",
  "Solanum americanum",
  "Solanum dulcamara",
  "Solanum nigrum",
  "Solanum americanum",
  "Solanum dulcamara",
  "Solanum nigrum",
  "Solanum nigrum",
  "Solanum dulcamara",
  "Solanum dulcamara",
  "Solanum dulcamara",
  "Trillium cernuum",
  "Botrychium boreale",
  "Achillea millefolium",
  "Quercus",
  "Quercus douglasii",
  "Quercus macrocarpa",
  "Quercus rubra",
  "Quercus velutina",
  "Quercus velutina",
  "Quercus robur",
  "Quercus canariensis",
  "Quercus macrocarpa",
  "Quercus rubra",
  "Quercus robur",
  "Quercus palustris",
  "Quercus rubra",
  "Quercus coccinea",
  "Quercus coccinea",
  "Quercus macrocarpa",
  "Quercus petraea",
  "Quercus coccinea",
  "Quercus rubra",
  "Quercus velutina",
  "Quercus palustris",
  "Quercus bicolor",
  "Quercus palustris",
  "Quercus bicolor",
  "Quercus alba",
  "Quercus velutina",
  "Allium",
  "Allium giganteum",
  "Allium cernuum",
  "Allium canadense",
  "Allium canadense",
  "Maclura pomifera",
  "Maclura pomifera",
  "Asclepias tuberosa",
  "Maclura pomifera",
  "Salix",
  "Cornus",
  "Cornus amomum",
  "Pastinaca sativa",
  "Daucus carota",
  "Achillea ptarmica",
  "Achillea ptarmica",
  "Achillea ptarmica",
  "Alliaria petiolata",
  "Cardamine concatenata",
  "Euphorbia peplus",
  "Phytolacca americana",
  "Platanus",
  "Plantago major",
  "Plantago major",
  "Plantago major",
  "Plantago major",
  "Plantago major",
  "Plantago major",
  "Asclepias tuberosa",
  "Phytolacca americana",
  "Toxicodendron radicans",
  "Solanum dulcamara",
  "Solanum dulcamara",
  "Phytolacca americana",
  "Veratrum viride",
  "Phytolacca americana",
  "Phytolacca americana",
  "Symplocarpus foetidus",
  "Symplocarpus foetidus",
  "Veratrum viride",
  "Alliaria petiolata",
  "Populus",
  "Papaveraceae",
  "Ilex decidua",
  "Primula vulgaris",
  "Daucus carota",
  "Anthriscus sylvestris",
  "Quercus velutina",
  "Solanum carolinense",
  "Ambrosia",
  "Ambrosia artemisiifolia",
  "Ambrosia trifida",
  "Ambrosia trifida",
  "Senecio",
  "Senecio jacobaea",
  "Senecio erucifolius",
  "Senecio aquaticus",
  "Senecio squalidus",
  "Senecio cineraria",
  "Daucus carota",
  "Rubus",
  "Rubus occidentalis",
  "Rubus occidentalis",
  "Cornus amomum",
  "Cercis",
  "Cercis siliquastrum",
  "Phytolacca americana",
  "Phytolacca americana",
  "Apocynum cannabinum",
  "Plantago major",
  "Oryza sativa",
  "Oryza glaberrima",
  "Plantago major",
  "Hesperis matronalis",
  "Hesperis matronalis",
  "Barbarea vulgaris",
  "Barbarea vulgaris",
  "Barbarea vulgaris",
  "Rosa",
  "Rosa multiflora",
  "Rosa virginiana",
  "Rosa virginiana",
  "Rosa multiflora",
  "Rosa virginiana",
  "Rosa multiflora",
  "Rosa virginiana",
  "Achillea millefolium",
  "Amelanchier alnifolia",
  "Alliaria petiolata",
  "Solanum dulcamara",
  "Phytolacca americana",
  "Rubus occidentalis",
  "Corydalis aurea",
  "Barbarea verna",
  "Amelanchier",
  "Amelanchier arborea",
  "Amelanchier arborea",
  "Amelanchier canadensis",
  "Amelanchier canadensis",
  "Amelanchier canadensis",
  "Oncosiphon suffruticosum",
  "Asclepias syriaca",
  "Asclepias incarnata",
  "Asclepias syriaca",
  "Symplocarpus foetidus",
  "Solanum dulcamara",
  "Galanthus",
  "Oxalis",
  "Veronica arvensis",
  "Veronica arvensis",
  "Nardostachys jatamansi",
  "Betula papyrifera",
  "Cornus amomum",
  "Ambrosia artemisiifolia",
  "Allium cristophii",
  "Ambrosia artemisiifolia",
  "Arbutus unedo",
  "Asclepias tuberosa",
  "Asclepias syriaca",
  "Achillea ptarmica",
  "Achillea ptarmica",
  "Amelanchier canadensis",
  "Achillea millefolium",
  "Viburnum prunifolium",
  "Asclepias tuberosa",
  "Asclepias syriaca",
  "Ipomoea batatas",
  "Ipomoea batatas",
  "Sonchus oleraceus",
  "Platanus",
  "Platanus racemosa",
  "Platanus occidentalis",
  "Heritiera fomes",
  "Excoecaria agallocha",
  "Tanacetum vulgare",
  "Achillea ptarmica",
  "Ambrosia artemisiifolia",
  "Camellia sinensis",
  "Ilex glabra",
  "Rubus occidentalis",
  "Rudbeckia laciniata",
  "Achillea millefolium",
  "Achillea millefolium",
  "Ambrosia artemisiifolia",
  "Sonchus oleraceus",
  "Cirsium arvense",
  "Cirsium arvense",
  "Cirsium arvense",
  "Sonchus arvensis",
  "Cirsium arvense",
  "Cirsium arvense",
  "Sonchus arvensis",
  "Cirsium arvense",
  "Cirsium arvense",
  "Sonchus oleraceus",
  "Sonchus oleraceus",
  "Carduus nutans",
  "Cirsium arvense",
  "Cirsium arvense",
  "Sonchus asper",
  "Cirsium arvense",
  "Sonchus asper",
  "Sonchus asper",
  "Sonchus arvensis",
  "Sonchus arvensis",
  "Cirsium arvense",
  "Thymus",
  "Thymus vulgaris",
  "Veratrum viride",
  "Nicotiana",
  "Cardamine concatenata",
  "Cardamine concatenata",
  "Cardamine concatenata",
  "Impatiens capensis",
  "Impatiens pallida",
  "Mimosa pudica",
  "Cardamine hirsuta",
  "Clematis virginiana",
  "Solanum carolinense",
  "Nicotiana glauca",
  "Trillium",
  "Asclepias tuberosa",
  "Ocimum santalum",
  "Hedyscepe canterburyana",
  "Cyperus alternifolius",
  "Vanilla",
  "Koelreuteria paniculata",
  "Mucuna pruriens",
  "Viburnum",
  "Viburnum prunifolium",
  "Viburnum rhytidophyllum",
  "Viola",
  "Saintpaulia",
  "Hesperis matronalis",
  "Hesperis matronalis",
  "Erythronium dens-canis",
  "Solanum dulcamara",
  "Scorzonera hispanica",
  "Clematis virginiana",
  "Clematis virginiana",
  "Dracunculus vulgaris",
  "Acacia",
  "Acacia ammobia",
  "Plantago major",
  "Plantago major",
  "Asclepias tuberosa",
  "Apocynum cannabinum",
  "Asclepias syriaca",
  "Lambertia",
  "Lambertia echinata",
  "Lambertia ericifolia",
  "Lambertia fairallii",
  "Lambertia formosa",
  "Lambertia formosa",
  "Lambertia ilicifolia",
  "Lambertia inermis",
  "Lambertia multiflora",
  "Lambertia orbifolia",
  "Lambertia rariflora",
  "Clematis virginiana",
  "Salix",
  "Salix exigua",
  "Salix gooddingii",
  "Cornus amomum",
  "Cornus amomum",
  "Asclepias tuberosa",
  "Rubus phoenicolasius",
  "Ilex verticillata",
  "Ilex verticillata",
  "Ilex glabra",
  "Ilex verticillata",
  "Barbarea vulgaris",
  "Barbarea verna",
  "Clematis virginiana",
  "Argyreia nervosa",
  "Ambrosia artemisiifolia",
  "Corydalis sempervirens",
  "Barbarea vulgaris",
  "Achillea",
  "Achillea millefolium",
  "Achillea filipendulina",
  "Achillea ptarmica",
  "Achillea tomentosa",
  "Rorippa sylvestris",
  "Cladrastis lutea",
  "Maclura pomifera",
  "Echinacea paradoxa",
  "Dioscorea",
  "Camellia yunnanensis",
  "Brachystegia spiciformis",
  "Curcuma zedoaria",
];
